name: Distribute

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  distribute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      # MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore
      # MYAPP_UPLOAD_KEY_ALIAS=
      # MYAPP_UPLOAD_STORE_PASSWORD=
      # MYAPP_UPLOAD_KEY_PASSWORD=
      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > my-upload-key.keystore.b64
          base64 -d -i my-upload-key.keystore.b64 > android/app/my-upload-key.keystore
          echo "MYAPP_UPLOAD_STORE_FILE=my-upload-key.keystore" >> gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=$KEYSTORE_KEY_ALIAS" >> gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=$KEYSTORE_STORE_PASSWORD" >> gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=$KEYSTORE_KEY_PASSWORD" >> gradle.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}

      - name: Build Beta
        run: |
          bundle exec fastlane beta

     